# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


workspace 'Example.xcworkspace'
target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ComponentBus', :path => '../'
  
  target 'HomeModule' do
    project 'HomeModule/HomeModule.xcodeproj'
  end
  
end
